import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

const coolvetica = localFont({
  src: '../../public/fonts/coolvetica.otf',
  variable: '--font-coolvetica',
});

const helvetica = localFont({
  src: '../../public/fonts/helvetica.ttf',
  variable: '--font-helvetica',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${coolvetica.variable} ${helvetica.variable} antialiased`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
