import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { Mona_Sans } from "next/font/google";

const mona_sans = Mona_Sans({
  variable: "--font-mona-sans",
  subsets: ["latin"],
});

const coolvetica = localFont({
  src: '../../public/fonts/coolvetica.otf',
  variable: '--font-coolvetica',
});

const helvetica = localFont({
  src: '../../public/fonts/helvetica.ttf',
  variable: '--font-helvetica',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mona_sans.variable} antialiased`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
